name: Build CI

on:
  merge_group:
    types: [checks_requested]
  pull_request:

jobs:
  build-erofs-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build HTML documentation
        run: make html
      - name: Upload artifact
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: erofs-docs-pr-${{ github.event.pull_request.number }}
          path: build/html/
          retention-days: 7
